title: Yubo ZHANG
description: E-mail - zhangyb at cs dot unc dot edu
logo: /assets/img/IMG_8870.jpeg
show_downloads: true 
google_analytics: ioBe1OPy6qPRoP74i-7hQIMw73gslveFoDmrkHIHYeY
theme: jekyll-theme-minimal
